#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PI 3.14159265359

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 600
#define WINDOW_FLAGS 0

#define MAP_WIDTH 7
#define MAP_HEIGHT 7
#define MAP_SQUARE_SIZE 75
#define MAP_BORDER_SIZE 0

#define PLAYER_SIZE 10
#define PLAYER_ANGLE_DELTA 1.0f
#define PLAYER_SPEED 0.2f
#define FOV 60  // in degrees

#define GAME_WIDTH 800
#define GAME_HEIGHT 600
#define RAYCASTING_PRECISION 100
#define SCALE 300

#define ERROR_CODE_SDL_INITIALIZATION 1
#define ERROR_CODE_SDL_CREATE_WINDOW_OR_RENDERER 2

#endif  // #ifndef CONSTANTS_H