#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 600
#define WINDOW_FLAGS 0

#define MAP_WIDTH 7
#define MAP_HEIGHT 7
#define MAP_SQUARE_SIZE 75
#define MAP_BORDER_SIZE 3

#define PLAYER_SIZE 10

#define ERROR_CODE_SDL_INITIALIZATION 1
#define ERROR_CODE_SDL_CREATE_WINDOW_OR_RENDERER 2

#endif  // #ifndef CONSTANTS_H