#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PI 3.14159265359

#define WINDOW_TITLE "Raycaster"
#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 600
#define WINDOW_FLAGS 0
#define RENDERER_FLAGS SDL_RENDERER_PRESENTVSYNC

#define MAP_WIDTH 20
#define MAP_HEIGHT 20
#define MAP_SQUARE_SIZE 24
#define MAP_BORDER_SIZE 1

#define PLAYER_SIZE 10
#define PLAYER_ANGLE_DELTA 1.0f
#define PLAYER_SPEED 0.01f
#define FOV 60  // in degrees

#define GAME_WIDTH 800
#define GAME_HEIGHT 600
#define SCALE 700
#define SHADE_CONSTANT 0.8f

#define ERROR_CODE_SDL_INITIALIZATION 1
#define ERROR_CODE_SDL_CREATE_WINDOW 2
#define ERROR_CODE_SDL_CREATE_RENDERER 3

#endif  // #ifndef CONSTANTS_H